name: CI

on: 
  schedule:
  - cron: "20 0 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Bash for GitHub Actions
      uses: jcblw/bash@1.0.0
      with:
        args: "bash piholeparser.sh"
